defaults: &DEFAULTS
  facebook_app_id: APP_ID
  facebook_secret: SECRET
  facebook_scope:
    - email
    - manage_pages
    - read_insights
  realtime_token: a4c52d99bcf822ded390766a4aecdcf2

development:
  <<: *DEFAULTS

test:
  <<: *DEFAULTS

production:
  <<: *DEFAULTS